field: fee69ac9-921e-42f0-8bb3-c83ad0f0f7c8
fieldLayouts:
  407c929c-283f-4b41-adc3-77c87bf9b135:
    tabs:
      -
        elements:
          -
            fieldUid: 4b8e3151-d432-4276-a08a-91a05e76a60c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 66fa6349-db2f-482c-a0d0-49b565cf243c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e62bb995-2c37-4c31-8af5-6b044d9302a5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 13d0b665-14b0-41b9-9a83-1c29450851a3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  13d0b665-14b0-41b9-9a83-1c29450851a3:
    contentColumnType: string
    fieldGroup: null
    handle: profileH
    instructions: ''
    name: 'Profiel H'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - c8fea00d-5255-4c94-8fcb-b4bf7046f008
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - db5416b5-b085-4e68-8dfc-61a0481640f2
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 9a11d228-7b11-471a-b14c-04f241e074e7
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 9b7bd8e9-8a7b-46f0-a967-1a954e90b527
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_8_profileh}}'
      fieldLayout: matrix
      maxRows: '1'
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  4b8e3151-d432-4276-a08a-91a05e76a60c:
    contentColumnType: string
    fieldGroup: null
    handle: profileM
    instructions: ''
    name: 'Profiel M'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 7b856d5c-1451-4e0d-bf90-a6d4d744bd78
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - f5845cff-dde6-444d-a40d-e00cbf4b1f89
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - df95fb13-3241-4c02-9c07-4cdb55ccfcef
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_8_profilem}}'
      fieldLayout: matrix
      maxRows: '1'
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  66fa6349-db2f-482c-a0d0-49b565cf243c:
    contentColumnType: string
    fieldGroup: null
    handle: profileS
    instructions: ''
    name: 'Profiel S'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - db78829c-bc47-4d2c-acb9-85c683a27cf5
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 50b5a058-67b2-4e6d-b1ca-619051df2716
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 393243fd-4905-4dea-ab4e-d082e0dd1b22
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - ac7f4ae1-6b50-45ec-9ba6-8b5959097a79
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_8_profiles}}'
      fieldLayout: matrix
      maxRows: '1'
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  e62bb995-2c37-4c31-8af5-6b044d9302a5:
    contentColumnType: string
    fieldGroup: null
    handle: profileC
    instructions: ''
    name: 'Profiel C'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 6c6e9c6f-dc32-464d-99a5-377097c341ba
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 78d66623-8ea6-4688-805f-a1a77065723d
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 0ba4ef4b-ae2e-48f0-9df7-4eee191ac8a8
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_8_profilec}}'
      fieldLayout: matrix
      maxRows: '1'
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: cta
name: Cta
sortOrder: 1
