field: 3fe02766-cb15-4477-9bb8-9ee757622da7
fieldLayouts:
  35384bb9-de07-4675-b003-1957eb27f325:
    tabs:
      -
        elements:
          -
            fieldUid: 41591e1e-379d-421a-ae9e-9273ac7c3420
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6d4acbd9-7fbe-46ab-b3c7-5a53dcde8dd3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  41591e1e-379d-421a-ae9e-9273ac7c3420:
    contentColumnType: text
    fieldGroup: null
    handle: featureTitle
    instructions: ''
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6d4acbd9-7fbe-46ab-b3c7-5a53dcde8dd3:
    contentColumnType: text
    fieldGroup: null
    handle: featureText
    instructions: ''
    name: Tekst
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: features
name: Features
sortOrder: 1
