field: 12f1fe9a-565b-4ec5-b495-02197e77bcb8
fieldLayouts:
  fe606f0c-9b02-4587-b00d-1d5ab9b088e8:
    tabs:
      -
        elements:
          -
            fieldUid: 539b813f-13b0-4f4e-a906-ee64a828b4bf
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b64ef10b-23a5-445e-9e46-2bc7c4fc4d95
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  539b813f-13b0-4f4e-a906-ee64a828b4bf:
    contentColumnType: text
    fieldGroup: null
    handle: featureTitle
    instructions: ''
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b64ef10b-23a5-445e-9e46-2bc7c4fc4d95:
    contentColumnType: text
    fieldGroup: null
    handle: featureText
    instructions: ''
    name: Tekst
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: features
name: Features
sortOrder: 1
