field: 33b5d60a-f6e0-4ab0-9e61-75474fb8d36f
fieldLayouts:
  86099587-cff0-44c3-8d24-3150f2ea2e91:
    tabs:
      -
        elements:
          -
            fieldUid: 295974a3-06fc-4908-80ce-54eaddf31b7a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9b8cf383-2699-4168-a5a7-ef363e117838
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  295974a3-06fc-4908-80ce-54eaddf31b7a:
    contentColumnType: text
    fieldGroup: null
    handle: featureTitle
    instructions: ''
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9b8cf383-2699-4168-a5a7-ef363e117838:
    contentColumnType: text
    fieldGroup: null
    handle: featureText
    instructions: ''
    name: Tekst
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: features
name: Features
sortOrder: 1
