field: 953a82b3-d644-4fc8-99b4-d5329a17a10f
fieldLayouts:
  e05c9ec0-a596-4128-a49d-cff1a422bbfb:
    tabs:
      -
        elements:
          -
            fieldUid: d9c67c62-3398-40a0-ab6e-04dcd82184a9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  d9c67c62-3398-40a0-ab6e-04dcd82184a9:
    contentColumnType: text
    fieldGroup: null
    handle: footerTitle
    instructions: ''
    name: footerTitel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: footer
name: Footer
sortOrder: 1
