field: 2a88ba81-a0a8-458e-a6dc-29d84c5da760
fieldLayouts:
  67fe3f55-0645-4a03-b027-16c67ddf7916:
    tabs:
      -
        elements:
          -
            fieldUid: 9784bc81-964f-421c-b038-1cd1a4d9711c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f670d39a-1995-4051-a46c-7d1035027e82
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 12065cdf-653d-4201-bc59-98e95e2a9c03
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 05c4a819-4572-4461-bed7-eb6530fc2ce2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  05c4a819-4572-4461-bed7-eb6530fc2ce2:
    contentColumnType: string
    fieldGroup: null
    handle: profileH
    instructions: ''
    name: 'Profiel H'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 173885ac-11e6-4dd9-9b6a-fe21e6e880e1
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - ecda82a7-0069-4110-a447-599933f0ee55
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 19d33297-0ddb-4c4b-8b63-2fdd829127f8
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_14_profileh}}'
      fieldLayout: matrix
      maxRows: '1'
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  12065cdf-653d-4201-bc59-98e95e2a9c03:
    contentColumnType: string
    fieldGroup: null
    handle: profileC
    instructions: ''
    name: 'Profiel C'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 1846d42f-a001-4128-88b0-e065ecd42646
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 69246cae-f2aa-4ad1-8eb3-c70ccd3fd486
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 9a303402-83cd-4f0a-8dfa-efe556662274
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - d504d773-6c66-462f-b595-c97369a1154d
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_14_profilec}}'
      fieldLayout: matrix
      maxRows: '1'
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  9784bc81-964f-421c-b038-1cd1a4d9711c:
    contentColumnType: string
    fieldGroup: null
    handle: profileM
    instructions: ''
    name: 'Profiel M'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 494a60d4-3796-48f2-a407-6460267a190d
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 837902f7-8bf8-4d4e-a4b7-23b2f28b5360
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - ea4ee7b2-0f06-4147-a246-303b4a21c546
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_14_profilem}}'
      fieldLayout: matrix
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  f670d39a-1995-4051-a46c-7d1035027e82:
    contentColumnType: string
    fieldGroup: null
    handle: profileS
    instructions: ''
    name: 'Profiel S'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 57b5bfc6-5ea3-4322-823c-ec9e62f672cc
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - f0eaf65f-9d91-467c-9935-cbb7fa17b5d0
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 3059a97f-3ce1-406d-b4c3-53ccac828ac7
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - e4216c6f-9d71-4f82-886b-8d95d14a3bef
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_14_profiles}}'
      fieldLayout: matrix
      maxRows: '1'
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: header
name: Header
sortOrder: 1
