field: 93bdad80-71a8-4b19-a253-592808c96ca4
fieldLayouts:
  f29b291f-acda-4b83-acca-e28a0a121116:
    tabs:
      -
        elements:
          -
            fieldUid: 6702112c-4a1a-498b-9ac1-5f010125e3f7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ba8eef2f-9003-42f7-adf9-c4c6f7ca21f6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7909b0dd-dfdd-4fdf-80e5-1ec5855e5e5e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 85e69f85-f7b6-465d-a58f-8f34723843a8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6702112c-4a1a-498b-9ac1-5f010125e3f7:
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: ''
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7909b0dd-dfdd-4fdf-80e5-1ec5855e5e5e:
    contentColumnType: string
    fieldGroup: null
    handle: blockImage
    instructions: ''
    name: Afbeelding
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:ca9ce813-806d-48ea-b8be-29f238c997a6'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:ca9ce813-806d-48ea-b8be-29f238c997a6'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:ca9ce813-806d-48ea-b8be-29f238c997a6'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  85e69f85-f7b6-465d-a58f-8f34723843a8:
    contentColumnType: string
    fieldGroup: null
    handle: blockPosition
    instructions: ''
    name: Positie
    searchable: false
    settings:
      default: left
      options:
        __assoc__:
          -
            - left
            - '1'
          -
            - center
            - ''
          -
            - right
            - '1'
          -
            - full
            - ''
          -
            - drop-left
            - ''
          -
            - drop-right
            - ''
    translationKeyFormat: null
    translationMethod: none
    type: rias\positionfieldtype\fields\Position
  ba8eef2f-9003-42f7-adf9-c4c6f7ca21f6:
    contentColumnType: text
    fieldGroup: null
    handle: blockText
    instructions: ''
    name: Tekst
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: project
name: Project
sortOrder: 1
