fieldLayouts:
  0c72d128-6c9d-47bc-a2d7-a563892e876f:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: b5dcefd0-35d6-4e93-83f7-900e66faef02
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 8698a67d-c895-4eb2-8db0-2f813ba45074
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 5208ad89-09a7-47e2-8d18-e0da555ebd80
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Inhoud
        sortOrder: 1
handle: employees
hasTitleField: true
name: Medewerkers
section: e26a9b65-7297-4505-98e8-645cc02f43ed
sortOrder: 1
titleFormat: null
