contentColumnType: string
fieldGroup: f66ec9f2-85d5-4105-a780-f700f447c882
handle: contentBlocks
instructions: ''
name: 'Content blokken'
searchable: true
settings:
  contentTable: '{{%matrixcontent_contentblocks}}'
  localizeBlocks: false
  maxBlocks: ''
  minBlocks: ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
