contentColumnType: string
fieldGroup: f66ec9f2-85d5-4105-a780-f700f447c882
handle: landingContentBlocks
instructions: ''
name: 'Landingspagina content blokken'
searchable: false
settings:
  contentTable: '{{%matrixcontent_landingcontentblocks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
