contentColumnType: string(255)
fieldGroup: f66ec9f2-85d5-4105-a780-f700f447c882
handle: linkedInUrl
instructions: ''
name: 'LinkedIn Url'
searchable: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
