contentColumnType: text
fieldGroup: f66ec9f2-85d5-4105-a780-f700f447c882
handle: mainTitle
instructions: ''
name: 'Hoofd titel'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
