contentColumnType: boolean
fieldGroup: f66ec9f2-85d5-4105-a780-f700f447c882
handle: overviewImagePadding
instructions: ''
name: 'Padding bij overzicht afbeelding'
searchable: true
settings:
  default: '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
