field: 505e24bf-1d60-4dbf-8603-f1b3a337eedb
fieldLayouts:
  701ac931-4397-42f9-a9e5-3e50d5b43691:
    tabs:
      -
        elements:
          -
            fieldUid: 6c1aa8ad-01ae-46f2-946c-5fc1d3beef56
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 74f416ca-4876-4e0e-bfb1-670f99d945d4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dafd407b-c8ac-4e3c-8929-136d3e9adb73
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6c1aa8ad-01ae-46f2-946c-5fc1d3beef56:
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: ''
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  74f416ca-4876-4e0e-bfb1-670f99d945d4:
    contentColumnType: string
    fieldGroup: null
    handle: blockImage
    instructions: ''
    name: Afbeelding
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:ca9ce813-806d-48ea-b8be-29f238c997a6'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:ca9ce813-806d-48ea-b8be-29f238c997a6'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:ca9ce813-806d-48ea-b8be-29f238c997a6'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  dafd407b-c8ac-4e3c-8929-136d3e9adb73:
    contentColumnType: string
    fieldGroup: null
    handle: featureOverview
    instructions: ''
    name: Featureoverzicht
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_featureoverview_5}}'
      maxBlocks: ''
      minBlocks: ''
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
