field: 0bd2c905-7de6-405c-983b-e5134afbbc17
fieldLayouts:
  3ac09eac-9a62-45c6-b913-77fb1ea9f946:
    tabs:
      -
        elements:
          -
            fieldUid: c5c4520d-babe-45d6-80e1-5768f3993d25
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6887db1a-4ae8-4839-a7dd-d25ab21b41c9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e1e0acdd-4fd3-4c7c-bdc2-7f56c835bfe2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6887db1a-4ae8-4839-a7dd-d25ab21b41c9:
    contentColumnType: string
    fieldGroup: null
    handle: blockImage
    instructions: ''
    name: Afbeelding
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:ca9ce813-806d-48ea-b8be-29f238c997a6'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:ca9ce813-806d-48ea-b8be-29f238c997a6'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:ca9ce813-806d-48ea-b8be-29f238c997a6'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c5c4520d-babe-45d6-80e1-5768f3993d25:
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: ''
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e1e0acdd-4fd3-4c7c-bdc2-7f56c835bfe2:
    contentColumnType: string
    fieldGroup: null
    handle: featureOverview
    instructions: ''
    name: Featureoverzicht
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_featureoverview_5}}'
      maxBlocks: ''
      minBlocks: ''
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
