field: c30b2b7f-c753-4886-befe-7e01f43a0858
fieldLayouts:
  cade81af-dda3-42c7-9912-b6d6c3992aa2:
    tabs:
      -
        elements:
          -
            fieldUid: eb0412de-1a64-491c-9935-22726d1cbf5b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bc058197-0569-4a84-ae05-fae884cb0055
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1b9cfa35-4c18-4da9-9354-7a144d952b28
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1b9cfa35-4c18-4da9-9354-7a144d952b28:
    contentColumnType: string
    fieldGroup: null
    handle: projectOverview
    instructions: ''
    name: Projectoverzicht
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_projectoverview}}'
      maxBlocks: ''
      minBlocks: ''
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  bc058197-0569-4a84-ae05-fae884cb0055:
    contentColumnType: text
    fieldGroup: null
    handle: overviewSubtitle
    instructions: ''
    name: Overzichtssubtitel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  eb0412de-1a64-491c-9935-22726d1cbf5b:
    contentColumnType: text
    fieldGroup: null
    handle: overviewTitle
    instructions: ''
    name: Overzichtstitel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
