field: e8d55b2b-a47e-405a-ae03-fa66f7672549
fieldLayouts:
  5be3ec5b-49da-49e7-8950-3cd1995971d3:
    tabs:
      -
        elements:
          -
            fieldUid: db3f8baf-630c-4a6c-a789-1bcd4ba26f82
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9a03b352-46f3-4f7e-943f-8950208a5dbc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9a03b352-46f3-4f7e-943f-8950208a5dbc:
    contentColumnType: string
    fieldGroup: null
    handle: teamOverview
    instructions: ''
    name: Teamoverzicht
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_teamoverview}}'
      maxBlocks: ''
      minBlocks: ''
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  db3f8baf-630c-4a6c-a789-1bcd4ba26f82:
    contentColumnType: text
    fieldGroup: null
    handle: overviewTitle
    instructions: ''
    name: Overzichtstitel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
