field: 095a6ec4-c210-4b56-87fd-83bc568bb498
fieldLayouts:
  d2d535c3-2b75-4892-a297-0d96fac3b472:
    tabs:
      -
        elements:
          -
            fieldUid: aa9895f0-eb4f-4df2-9cb9-4fbe64e98f68
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 33b5d60a-f6e0-4ab0-9e61-75474fb8d36f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  33b5d60a-f6e0-4ab0-9e61-75474fb8d36f:
    contentColumnType: string
    fieldGroup: null
    handle: featureOverview
    instructions: ''
    name: Featureoverzicht
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_featureoverview_2}}'
      maxBlocks: ''
      minBlocks: ''
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  aa9895f0-eb4f-4df2-9cb9-4fbe64e98f68:
    contentColumnType: text
    fieldGroup: null
    handle: overviewTitle
    instructions: ''
    name: Overzichtstitel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
