enableVersioning: true
handle: jobs
name: Vacatures
previewTargets:
  -
    label: 'Primaire invoer-pagina'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  b3528ed7-d45e-4ed6-8279-c6d3463caa6d:
    enabledByDefault: true
    hasUrls: true
    template: jobs/_entry
    uriFormat: 'vacatures/{slug}'
structure:
  maxLevels: null
  uid: 6285dd91-f775-4959-8b01-eb61d51469fe
type: structure
